import mongoose, { Schema, Document, Types } from "mongoose";
import { getNextReportNumber } from "../utils/activityReportHelpers.js";

// Sub-schema for attendance records
const attendanceRecordSchema = new Schema(
  {
    employeeId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    status: {
      type: String,
      enum: ["present", "absent", "late", "vacation", "sick", "unpaid", "compensatory"],
      required: true,
    },
    absenceReason: { type: String }, // e.g., "Enfermedad", "Falta injustificada"
    replacementId: { type: Schema.Types.ObjectId, ref: "User" },
    overtimeHours: { type: Number, default: 0 },
    inTime: { type: String }, // Real Entry Time
    outTime: { type: String }, // Real Exit Time
    scheduleInTime: { type: String }, // Expected Entry
    scheduleOutTime: { type: String }, // Expected Exit
    notes: { type: String },
  },
  { _id: true },
);

export interface IActivityReport extends Document {
  tenantId: Types.ObjectId;
  userId: Types.ObjectId;
  reportNumber?: string;
  date: string; // YYYY-MM-DD
  projectId?: Types.ObjectId;
  areaId?: Types.ObjectId;
  hasActivity: boolean;
  comments?: string;
  attendance: Types.DocumentArray<any>;
  submittedAt: Date;
}

const activityReportSchema = new Schema<IActivityReport>(
  {
    tenantId: { type: Schema.Types.ObjectId, ref: "Tenant", required: true },
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    reportNumber: { type: String, trim: true, uppercase: true }, // Not required initially, generated by hook
    date: { type: String, required: true }, // Format YYYY-MM-DD
    projectId: { type: Schema.Types.ObjectId, ref: "Project" },
    areaId: { type: Schema.Types.ObjectId, ref: "Area" }, // Optional linkage to Area
    hasActivity: { type: Boolean, default: true },
    comments: { type: String },
    attendance: [attendanceRecordSchema],
    submittedAt: { type: Date, default: Date.now },
  },
  { timestamps: true, collection: "activity_reports" },
);

// Indexes
activityReportSchema.index({ tenantId: 1, userId: 1, date: -1 });
activityReportSchema.index({ tenantId: 1, reportNumber: 1 }, { unique: true, sparse: true }); // Sparse in case older records don't have it immediately, though we aim to have it.

// Pre-validate hook for reportNumber
activityReportSchema.pre("validate", async function (next) {
  if (!this.isNew || this.reportNumber) {
    return next();
  }

  const maxRetries = 5;
  let attempt = 0;

  while (attempt < maxRetries) {
    try {
      // Use dynamic import or model retrieval to avoid circular dependency if imported directly (though here we import helper, helper imports model dynamically now)
      // Actually, since we fixed the helper to use mongoose.model("ActivityReport"), we can just call the helper.
      // But we need to ensure Tenant model is available.

      // Ensure Tenant model is loaded (usually it is app-wide, but safe check)
      // const Tenant = mongoose.model("Tenant");
      // If we don't assume Tenant model is already compiled, we might need to import it.
      // Typically in this project, models might be auto-loaded.
      // Let's assume Tenant is available or fetch it via checking collection directly if needed,
      // but standard Mongoose pattern is `mongoose.model('Tenant')`.

      const Tenant = mongoose.models.Tenant || mongoose.model("Tenant");
      const tenant = await Tenant.findById(this.tenantId);

      if (!tenant) {
        // If tenant not found, we can't generate prefix. Fallback or error?
        // Let's log and use a default prefix to avoid complete failure
        console.warn("Tenant not found for report number generation");
        this.reportNumber = `UNK-REG-${Date.now()}`; // Fallback
        return next();
      }

      const prefix = tenant.slug ? tenant.slug.toUpperCase().slice(0, 3) : "UNK";
      this.reportNumber = await getNextReportNumber(this.tenantId, prefix);

      return next();
    } catch (error: any) {
      if (error.code === 11000 && attempt < maxRetries - 1) {
        attempt++;
        await new Promise((resolve) => setTimeout(resolve, Math.random() * 100)); // Jitter
        continue;
      }
      return next(error as Error); // Pass error if not duplicate key or retries exhausted
    }
  }

  return next(new Error("Failed to generate unique report number after multiple attempts"));
});

export const ActivityReport = mongoose.model<IActivityReport>("ActivityReport", activityReportSchema);
